---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
data("instacart")
```

```{r}
popular20_aisle = instacart %>% 
  group_by(aisle) %>% 
  summarise(count = n()) %>% 
  arrange(-count) %>% 
  top_n(20) %>% 
  mutate(rank = 1:20,
         text_label = str_c(aisle, " is No.", rank, " popular aisle with ", count, " orders"))
```


```{r}
order_count = instacart %>% 
  group_by(user_id) %>% 
  summarise(count = n()) %>% 
  filter(count > 30)

order_more30_id = order_count %>% 
  pull(user_id)

days_since_prior_order = instacart %>% 
  filter(user_id %in% order_more30_id) %>% 
  select(user_id, days_since_prior_order) 

days_since_prior_order = days_since_prior_order[!duplicated(days_since_prior_order[,1]),]

shop_interval_VS_order_count = left_join(order_count, days_since_prior_order) %>% 
  mutate(days_since_prior_order = str_c(days_since_prior_order, " day(s)"))
```


```{r}
interval_VS_count_mean_median = left_join(order_count, days_since_prior_order) %>% 
  group_by(days_since_prior_order) %>% 
  summarise(mean = mean(count),
            median = median(count)) %>% 
  pivot_longer(
    mean:median, 
    names_to = "measure_type",
    values_to = "statistics"
  )
```

```{r}
aisles = popular20_aisle %>% 
  pull(aisle)
```

```{r}
axis_x = list(tickangle = '-45')
```

Top 20 aisles
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### The 20 most popular aisle 

```{r}
popular20_aisle %>% 
  mutate(aisle = fct_reorder(aisle, -count)) %>% 
  plot_ly(x = ~aisle, y = ~count, type = "bar", text = ~text_label,
          color = ~aisle, colors = "viridis") %>% 
  layout(xaxis = axis_x)
```

### Shopping interval of the 20 most popular aisle for those who have use instacart for more than 10 times

```{r}
instacart %>% 
  filter(aisle %in% aisles, order_number > 10) %>% 
  mutate(aisle = fct_reorder(aisle, days_since_prior_order)) %>% 
  plot_ly(y = ~days_since_prior_order, color = ~aisle, type = "box",  colors = "viridis") %>% 
  layout(xaxis = axis_x)
```

Time & Count
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Relationship between days since prior order and number of one-time purchases for those purchase more than 30 items in one order

```{r}
shop_interval_VS_order_count %>% 
  mutate(days_since_prior_order = fct_reorder(days_since_prior_order, count)) %>% 
  plot_ly(y = ~count, color = ~days_since_prior_order, type = "box",  colors = "viridis") %>% 
  layout(xaxis = axis_x)

```


Column {data-width=500}
-----------------------------------------------------------------------
### Relationship between days since prior order and number of one-time purchases for those purchase more than 30 items in one order

```{r}
plot = interval_VS_count_mean_median %>% 
  ggplot(aes(x = days_since_prior_order, y = statistics, color = measure_type)) +
  geom_point() +
  geom_smooth(se = FALSE)
ggplotly(plot)
``` 

